# fly.toml app configuration file generated for sibook-db on 2023-09-04T15:52:54+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sibook-db"
primary_region = "cdg"

kill_signal = "SIGTERM"
kill_timeout = 300
services = []

[checks]

  [checks.pg]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/flycheck/pg"
    port = 5500
    timeout = "10s"
    type = "http"

  [checks.role]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/flycheck/role"
    port = 5500
    timeout = "10s"
    type = "http"

  [checks.vm]
    grace_period = "1s"
    interval = "1m"
    method = "get"
    path = "/flycheck/vm"
    port = 5500
    timeout = "10s"
    type = "http"

[build]

[env]
  BACKEND_STORE = "consul"
  PRIMARY_REGION = "ord"

[experimental]
  allowed_public_ports = []
  auto_rollback = false
  enable_consul = true
  private_network = true

[metrics]
  path = "/metrics"
  port = 9187

[[mounts]]
  destination = "/data"
  source = "pg_data"
